default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>
development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>
test:
  <<: *default
  database: <%= "#{Rails.application.class.to_s.parameterize(separator: '_')}_test" %>
production:
  primary: &primary_production
    <<: *default
  cache:
    <<: *primary_production
    database: <%= "#{Rails.application.class.to_s.parameterize(separator: '_')}_cache" %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= "#{Rails.application.class.to_s.parameterize(separator: '_')}_queue" %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= "#{Rails.application.class.to_s.parameterize(separator: '_')}_cable" %>
    migrations_paths: db/cable_migrate
